<?php
/** @package Petfinder::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("MascotaMap.php");

/**
 * MascotaDAO provides object-oriented access to the mascota table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Petfinder::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class MascotaDAO extends Phreezable
{
	/** @var int */
	public $Pkmascota;

	/** @var string */
	public $Nombre;

    /** @var string */
    public $Genero;

	/** @var string */
	public $Tamano;

	/** @var string */
	public $Color;

	/** @var int */
	public $FktipoMascota;

	/** @var int */
	public $Fkraza;

	/** @var int */
	public $Estado;

}
?>