<?php
/** @package Petfinder::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PosterMap.php");

/**
 * PosterDAO provides object-oriented access to the poster table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Petfinder::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PosterDAO extends Phreezable
{
	/** @var int */
	public $Pkposter;

	/** @var int */
	public $Fkusuario;

	/** @var int */
	public $Fkmascota;

	/** @var int */
	public $FktipoPoster;

	/** @var string */
	public $Latitud;

	/** @var string */
	public $Longitud;

	/** @var float */
	public $Recompensa;

	/** @var string */
	public $TipoMoneda;

	/** @var string */
	public $Descripcion;

	/** @var string */
	public $Fecha;

	/** @var string */
	public $Hora;



}
?>