<?php
/** @package Petfinder::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("TipoPosterMap.php");

/**
 * TipoPosterDAO provides object-oriented access to the tipo_poster table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Petfinder::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class TipoPosterDAO extends Phreezable
{
	/** @var int */
	public $PktipoPoster;

	/** @var string */
	public $Nombre;

	/** @var string */
	public $Descripcion;

	/** @var float */
	public $Precio;

	/** @var string */
	public $TipoMoneda;



}
?>